#!/bin/bash
export PYSPARK_DRIVER_PYTHON=/Anaconda/bin/jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="notebook --NotebookApp.open_browser=True --NotebookApp.ip='*' --NotebookApp.port=8888"
export PYSPARK_PYTHON=/anaconda/bin/python2.7
/usr/local/spark/bin/pyspark --driver-memory 10g --executor-memory 10g
